/**
 * Stable, transport-independent error identifiers shared by services and clients.
 *
 * Values are part of the public wire contract. Add new values; never repurpose an
 * existing value for a different failure.
 */
export enum ErrorCode {
  UNAUTHENTICATED = "UNAUTHENTICATED",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  ACCESS_DENIED = "ACCESS_DENIED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  NETWORK_ERROR = "NETWORK_ERROR",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  KAFKA_UNAVAILABLE = "KAFKA_UNAVAILABLE",
  CACHE_UNAVAILABLE = "CACHE_UNAVAILABLE",
  MINIO_UNAVAILABLE = "MINIO_UNAVAILABLE",

  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  ACCOUNT_DISABLED = "ACCOUNT_DISABLED",
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  DEVICE_NOT_TRUSTED = "DEVICE_NOT_TRUSTED",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  TOKEN_REVOKED = "TOKEN_REVOKED",
  UNAUTHORIZED_TENANT = "UNAUTHORIZED_TENANT",
  STEP_UP_REQUIRED = "STEP_UP_REQUIRED",
  ACCESS_BLOCKED = "ACCESS_BLOCKED",
  AUTHENTICATION_INPUT_INVALID = "AUTHENTICATION_INPUT_INVALID",
  AUTHENTICATION_STATE_INVALID = "AUTHENTICATION_STATE_INVALID",
  GUEST_SIGNUP_FAILED = "GUEST_SIGNUP_FAILED",
  IDENTITY_PROVIDER_UNAVAILABLE = "IDENTITY_PROVIDER_UNAVAILABLE",

  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS",
  USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS",
  USER_STATE_INVALID = "USER_STATE_INVALID",

  EVENT_NOT_FOUND = "EVENT_NOT_FOUND",
  EVENT_ALREADY_EXISTS = "EVENT_ALREADY_EXISTS",
  EVENT_CLOSED = "EVENT_CLOSED",
  EVENT_ACCESS_DENIED = "EVENT_ACCESS_DENIED",
  EVENT_INVALID_INPUT = "EVENT_INVALID_INPUT",
  EVENT_MEMBER_NOT_FOUND = "EVENT_MEMBER_NOT_FOUND",
  EVENT_TIMELINE_NOT_FOUND = "EVENT_TIMELINE_NOT_FOUND",
  EVENT_MEDIA_NOT_FOUND = "EVENT_MEDIA_NOT_FOUND",
  EVENT_MEDIA_VARIANT_NOT_FOUND = "EVENT_MEDIA_VARIANT_NOT_FOUND",
  EVENT_TOKEN_INVALID = "EVENT_TOKEN_INVALID",
  SEAT_ALLOCATION_EXCEEDED = "SEAT_ALLOCATION_EXCEEDED",
  GEOCODING_UNAVAILABLE = "GEOCODING_UNAVAILABLE",

  SEAT_NOT_FOUND = "SEAT_NOT_FOUND",
  SEAT_OCCUPIED = "SEAT_OCCUPIED",
  SEAT_ALREADY_RESERVED = "SEAT_ALREADY_RESERVED",
  SEAT_CAPACITY_EXCEEDED = "SEAT_CAPACITY_EXCEEDED",
  SEAT_UNAVAILABLE = "SEAT_UNAVAILABLE",
  SEAT_ASSIGNMENT_NOT_FOUND = "SEAT_ASSIGNMENT_NOT_FOUND",
  SEAT_ACCESS_DENIED = "SEAT_ACCESS_DENIED",
  SEAT_EVENT_MISMATCH = "SEAT_EVENT_MISMATCH",
  SEAT_VERIFICATION_TOKEN_INVALID = "SEAT_VERIFICATION_TOKEN_INVALID",
  SECTION_NOT_FOUND = "SECTION_NOT_FOUND",
  SECTION_CONFLICT = "SECTION_CONFLICT",
  TABLE_NOT_FOUND = "TABLE_NOT_FOUND",
  TABLE_CONFLICT = "TABLE_CONFLICT",
  LAYOUT_VERSION_NOT_FOUND = "LAYOUT_VERSION_NOT_FOUND",

  INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND",
  INVITATION_ALREADY_EXISTS = "INVITATION_ALREADY_EXISTS",
  INVITATION_ALREADY_APPROVED = "INVITATION_ALREADY_APPROVED",
  INVITATION_ALREADY_REJECTED = "INVITATION_ALREADY_REJECTED",
  INVITATION_LIMIT_REACHED = "INVITATION_LIMIT_REACHED",
  INVITATION_ACCESS_DENIED = "INVITATION_ACCESS_DENIED",
  INVITATION_INVALID_INPUT = "INVITATION_INVALID_INPUT",
  INVITATION_PREVIEW_FAILED = "INVITATION_PREVIEW_FAILED",
  INVITATION_UPLOAD_INVALID = "INVITATION_UPLOAD_INVALID",
  RSVP_NOT_SUBMITTED = "RSVP_NOT_SUBMITTED",
  RSVP_NOT_ACCEPTED = "RSVP_NOT_ACCEPTED",
  RSVP_ALREADY_ACCEPTED = "RSVP_ALREADY_ACCEPTED",
  MISSING_GUEST_NAME = "MISSING_GUEST_NAME",
  MISSING_PENDING_CONTACT = "MISSING_PENDING_CONTACT",
  MISSING_RSVP_CONTACT_DETAILS = "MISSING_RSVP_CONTACT_DETAILS",
  MISSING_CONTACT_METHOD = "MISSING_CONTACT_METHOD",

  TICKET_NOT_FOUND = "TICKET_NOT_FOUND",
  TICKET_REVOKED = "TICKET_REVOKED",
  TICKET_ALREADY_REDEEMED = "TICKET_ALREADY_REDEEMED",
  TICKET_ALREADY_SCANNED = "TICKET_ALREADY_SCANNED",
  TICKET_ALREADY_EXISTS = "TICKET_ALREADY_EXISTS",
  TICKET_ACCESS_DENIED = "TICKET_ACCESS_DENIED",
  TICKET_DEVICE_ALREADY_BOUND = "TICKET_DEVICE_ALREADY_BOUND",
  TICKET_DEVICE_KEY_INVALID = "TICKET_DEVICE_KEY_INVALID",
  TICKET_NONCE_UNINITIALIZED = "TICKET_NONCE_UNINITIALIZED",
  TICKET_VERIFICATION_TOKEN_INVALID = "TICKET_VERIFICATION_TOKEN_INVALID",
  TICKET_TOKEN_INVALID = "TICKET_TOKEN_INVALID",

  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_DELIVERY_FAILED = "NOTIFICATION_DELIVERY_FAILED",
  NOTIFICATION_CHANNEL_UNAVAILABLE = "NOTIFICATION_CHANNEL_UNAVAILABLE",
  NOTIFICATION_STATE_INVALID = "NOTIFICATION_STATE_INVALID",
  NOTIFICATION_INPUT_INVALID = "NOTIFICATION_INPUT_INVALID",
  TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND",
  TEMPLATE_ALREADY_EXISTS = "TEMPLATE_ALREADY_EXISTS",
  TEMPLATE_STATE_INVALID = "TEMPLATE_STATE_INVALID",
  CHAT_NOT_FOUND = "CHAT_NOT_FOUND",
  CHAT_ACCESS_DENIED = "CHAT_ACCESS_DENIED",
  CHAT_STATE_INVALID = "CHAT_STATE_INVALID",
  CHAT_ASSIGNMENT_CONFLICT = "CHAT_ASSIGNMENT_CONFLICT",
  MESSAGE_INPUT_INVALID = "MESSAGE_INPUT_INVALID",

  STORAGE_ERROR = "STORAGE_ERROR",
  CACHE_PARSE_ERROR = "CACHE_PARSE_ERROR",
  CACHE_VALIDATION_ERROR = "CACHE_VALIDATION_ERROR",
}

const errorCodeValues = new Set<string>(Object.values(ErrorCode));

export const ERROR_CODES: readonly ErrorCode[] = Object.freeze(
  Object.values(ErrorCode),
);

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === "string" && errorCodeValues.has(value);
}
