/**
 * Represents user interests.
 * Mirrors the Prisma enum `InterestType`.
 */
export enum InterestType {
  BANK_PRODUCTS_AND_SERVICES = 'BANK_PRODUCTS_AND_SERVICES',
  TECHNOLOGY_AND_INNOVATION = 'TECHNOLOGY_AND_INNOVATION',
  SUSTAINABLE_FINANCE = 'SUSTAINABLE_FINANCE',
  INVESTMENTS = 'INVESTMENTS',
  SAVING_AND_FINANCE = 'SAVING_AND_FINANCE',
  CREDIT_AND_DEBT = 'CREDIT_AND_DEBT',
  REAL_ESTATE = 'REAL_ESTATE',
  INSURANCE = 'INSURANCE',
  TRAVEL = 'TRAVEL',
  CLASSIC = 'CLASSIC',
  ROCK = 'ROCK',
  HIPHOP = 'HIPHOP',
  RAP = 'RAP',
  FOOTBALL = 'FOOTBALL',
  SOCCER = 'SOCCER',
  RUGBY = 'RUGBY',
  BASKETBALL = 'BASKETBALL',
  FINANCIAL_EDUCATION_AND_COUNSELING = 'FINANCIAL_EDUCATION_AND_COUNSELING',
}
